DRFStudy/urls.py
from django.conf.urls import url
from rest_framework import routers

from DRFStudy.views import book_test_view, book_drf_view, api_view, generic_api_view, mixin_generic_api_view, \
    third_view, view_set_view, model_view_set

router = routers.DefaultRouter()
router.register("books", book_drf_view.BookViewSet, basename="drf_books")
router.register("book_info", model_view_set.BookInfoModelViewSet, basename="book_info")

urlpatterns = [
    url(r'^test_books/$', book_test_view.BooksAPIVIew.as_view()),
    url(r'^test_books/(?P<pk>\d+)/$', book_test_view.BookAPIView.as_view()),

    url(r'^api_books/$', api_view.BookListAPIView.as_view()),
    url(r'^api_books/(?P<book_id>\d+)/$', api_view.BookDetailAPIView.as_view()),

    url(r'^generic_api_books/$', generic_api_view.BookListGenericAPIView.as_view()),
    url(r'^generic_api_books/(?P<pk>\d+)/$', generic_api_view.BookDetailGenericAPIView.as_view()),

    url(r'^mixin_generic_api_books/$', mixin_generic_api_view.BookListMixinGenericAPIView.as_view()),
    url(r'^mixin_generic_api_books/(?P<book_id>\d+)/$', mixin_generic_api_view.BookDetailMixinGenericAPIView.as_view()),

    url(r'^third_view/$', third_view.BookListThirdView.as_view()),
    url(r'^third_view/(?P<pk>\d+)/$', third_view.BookDetailThirdView.as_view()),

    url(r'^view_set/$', view_set_view.BookViewSet.as_view({"get": "list"})),
    url(r'^view_set/(?P<pk>\d+)/$', view_set_view.BookViewSet.as_view({"get": "retrieve"})),

    url(r'^readonly_view_set/$', view_set_view.BookReadOnlyModelViewSet.as_view({"get": "list"})),
    url(r'^readonly_view_set/(?P<pk>\d+)/$', view_set_view.BookReadOnlyModelViewSet.as_view({"get": "retrieve"})),

    url(r'^model_view_set/$', view_set_view.BookModelViewSet.as_view({"get": "list", "post": "create"})),
    url(r'^model_view_set/(?P<pk>\d+)/$',
        view_set_view.BookModelViewSet.as_view({"get": "retrieve", 'put': 'update', 'delete': 'destroy'})),
    url(r'^model_view_set/bread_book/$', view_set_view.BookModelViewSet.as_view({"get": "bread_book"})),
    url(r'^model_view_set/update_partial_book_bread/(?P<pk>\d+)/$',
        view_set_view.BookModelViewSet.as_view({"put": "update_partial_book_bread"})),

]
urlpatterns += router.urls

DjangoStudy/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^docs/', include_docs_urls(title='我的API文档')),
    url('^view/', include(('ViewStudy.urls', 'view'), namespace="view")),
    url('^file/', include(('FileStudy.urls', 'file'), namespace="file")),
    url('^advance/', include(('AdvanceStudy.urls', 'advance'), namespace="advance")),
    url('^rest/', include('RestStudy.urls')),
    url('^drf/', include('DRFStudy.urls')),
]

FileStudy/urls.py
from django.conf.urls import url
from FileStudy import views

urlpatterns = [
    url(r'^hello_world/$', views.hello_world),
    url(r'^index/$', views.index),
    url(r'^upload_file/$', views.upload_file, name="upload_file"),
    url(r'^image_upload/$', views.image_upload, name="image_upload"),
    url(r'^mine/$', views.mine, name="mine")
]

templates/file/imageUpload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ImageUpload</title>
</head>
<body>
<form action="{% url 'file:image_upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <span>用户名：</span>
    <label>
        <input type="text" name="username" placeholder="请输入用户名">
    </label>
    <br>
    <span>文件：</span>
    <input type="file" name="icon">
    <br>
    <button>上传</button>
</form>
</body>
</html>

templates/file/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
<h2>双击666</h2>
<h2>{{ username }}</h2>
</body>
</html>

templates/file/mine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mine</title>
</head>
<body>
<h3>{{ username }}</h3>
<img src="{{ icon_url }}" alt="{{ username }}">
</body>
</html>

templates/file/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload</title>
</head>
<body>
<form action="{% url 'file:upload_file' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <span>文件：</span>
    <input type="file" name="icon">
    <br>
    <input type="submit" value="上传">
</form>
</body>
</html>