DRFStudy/urls.py
from django.conf.urls import url
from rest_framework import routers

from DRFStudy.views import book_test_view, book_drf_view, api_view, generic_api_view, mixin_generic_api_view, \
    third_view, view_set_view, model_view_set

router = routers.DefaultRouter()
router.register("books", book_drf_view.BookViewSet, basename="drf_books")
router.register("book_info", model_view_set.BookInfoModelViewSet, basename="book_info")

urlpatterns = [
    url(r'^test_books/$', book_test_view.BooksAPIVIew.as_view()),
    url(r'^test_books/(?P<pk>\d+)/$', book_test_view.BookAPIView.as_view()),

    url(r'^api_books/$', api_view.BookListAPIView.as_view()),
    url(r'^api_books/(?P<book_id>\d+)/$', api_view.BookDetailAPIView.as_view()),

    url(r'^generic_api_books/$', generic_api_view.BookListGenericAPIView.as_view()),
    url(r'^generic_api_books/(?P<pk>\d+)/$', generic_api_view.BookDetailGenericAPIView.as_view()),

    url(r'^mixin_generic_api_books/$', mixin_generic_api_view.BookListMixinGenericAPIView.as_view()),
    url(r'^mixin_generic_api_books/(?P<book_id>\d+)/$', mixin_generic_api_view.BookDetailMixinGenericAPIView.as_view()),

    url(r'^third_view/$', third_view.BookListThirdView.as_view()),
    url(r'^third_view/(?P<pk>\d+)/$', third_view.BookDetailThirdView.as_view()),

    url(r'^view_set/$', view_set_view.BookViewSet.as_view({"get": "list"})),
    url(r'^view_set/(?P<pk>\d+)/$', view_set_view.BookViewSet.as_view({"get": "retrieve"})),

    url(r'^readonly_view_set/$', view_set_view.BookReadOnlyModelViewSet.as_view({"get": "list"})),
    url(r'^readonly_view_set/(?P<pk>\d+)/$', view_set_view.BookReadOnlyModelViewSet.as_view({"get": "retrieve"})),

    url(r'^model_view_set/$', view_set_view.BookModelViewSet.as_view({"get": "list", "post": "create"})),
    url(r'^model_view_set/(?P<pk>\d+)/$',
        view_set_view.BookModelViewSet.as_view({"get": "retrieve", 'put': 'update', 'delete': 'destroy'})),
    url(r'^model_view_set/bread_book/$', view_set_view.BookModelViewSet.as_view({"get": "bread_book"})),
    url(r'^model_view_set/update_partial_book_bread/(?P<pk>\d+)/$',
        view_set_view.BookModelViewSet.as_view({"put": "update_partial_book_bread"})),

]
urlpatterns += router.urls

DjangoStudy/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^docs/', include_docs_urls(title='我的API文档')),
    url('^view/', include(('ViewStudy.urls', 'view'), namespace="view")),
    url('^file/', include(('FileStudy.urls', 'file'), namespace="file")),
    url('^advance/', include(('AdvanceStudy.urls', 'advance'), namespace="advance")),
    url('^rest/', include('RestStudy.urls')),
    url('^drf/', include('DRFStudy.urls')),
]

ViewStudy/urls.py
from django.conf.urls import url

from ViewStudy import views, cookie_view, session_view, token_view

urlpatterns = [
    url(r'^hello_world$', views.hello_world),
    url(r'^students/$', views.students),
    url(r'^students/(\d+)/$', views.student),
    url(r'^grades/$', views.grades),
    url(r'^get_date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$', views.get_date, name="get_date"),
    url(r"^learn/$", views.learns, name="learn"),

    url(r"^set_cookie/$", cookie_view.set_cookie),
    url(r"^get_cookie/$", cookie_view.get_cookie),
    url(r"^login/$", cookie_view.login, name="login"),
    url(r"^do_login/$", cookie_view.do_login, name="do_login"),
    url(r"^mine/$", cookie_view.mine, name="mine"),
    url(r"^logout/$", cookie_view.logout, name="logout"),

    url(r"^session_login/$", session_view.session_login, name="session_login"),
    url(r"^session_mine/$", session_view.session_mine, name="session_mine"),
    url(r"^session_logout/$", session_view.session_logout, name="session_logout"),

    url(r"^register/$", token_view.register, name="register"),
    url(r"^student_login/$", token_view.student_login, name="student_login"),
    url(r"^student_mine/$", token_view.student_mine, name="student_mine"),

]

templates/grade_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GradeList</title>
</head>
<body>
<ul>
    {% for grade in grade_list %}
        <li><a href="/view/students/{{ grade.id }}">{{ grade.g_name }}</a></li>
    {% endfor %}
</ul>
<hr>
<a href="{% url 'view:learn' %}">go learn</a>
<a href="{% url 'view:get_date' year=2018 month=10 day=01 %}">get_date</a>
</body>
</html>

templates/grade_student_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GradeStudentList</title>
</head>
<body>
<ul>
    {% for student in student_list %}
        <li>{{ student.s_name }}</li>
    {% endfor %}
</ul>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<form action="{% url 'view:do_login' %}" method="post">
    {% csrf_token %}
    <span>用户名：</span>
    <label>
        <input type="text" placeholder="输入" name="uname">
    </label>
    <button>登录</button>

</form>
</body>
</html>

templates/mine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mine</title>
</head>
<body>
<h2>欢迎回来：{{ uname }}</h2>
<a href="{% url 'view:logout' %}">退出</a>
</body>
</html>

templates/sessionLogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SessionLogin</title>
</head>
<body>
<form action="{% url 'view:session_login' %}" method="post">
    {% csrf_token %}
    <span>用户名：</span>
    <label>
        <input type="text" placeholder="输入" name="username">
    </label>
    <button>登录</button>

</form>
</body>
</html>

templates/sessionMine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SessionMine</title>
</head>
<body>
<h2>欢迎回来：{{ username }}</h2>
<a href="{% url 'view:session_logout' %}">退出</a>
</body>
</html>

templates/studentLogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StudentLogin</title>
</head>
<body>
<form action="{% url 'view:student_login' %}" method="post">
    <span>用户名：</span>
    <label>
        <input type="text" placeholder="输入用户名" name="username">
    </label>
    <br>
    <span>密码：</span>
    <label>
        <input type="text" placeholder="输入密码" name="password">
    </label>
    <button>登录</button>

</form>
</body>
</html>

templates/studentRegister.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StudentRegister</title>
</head>
<body>
<form action="{% url 'view:register' %}" method="post">
    {% csrf_token %}
    <span>用户名：</span>
    <label>
        <input type="text" placeholder="输入用户名" name="username">
    </label>
    <br>
    <span>密码：</span>
    <label>
        <input type="text" placeholder="输入密码" name="password">
    </label>
    <button>注册</button>

</form>
</body>
</html>